version: "3"
services:
 redis:
  image: redis:alpine
  ports:
    - "6377:6379"
  volumes:
    - redis_data:/data
  networks:
    - app-network
  hostname: redis
 kazan_reds_bot:
   build:
     context: .
     dockerfile: Dockerfile
   image: kzn_reds_app
   container_name: kazan_reds_bot
   env_file: .env
   environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
   expose:
     - 8200  
   networks:
    - app-network
   restart: always
   command: python /app/main.py
# kzn_reds_pg:
#   image: postgres:14.2
#   hostname: kzn_reds_pg
#   environment:
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: postgres
#     POSTGRES_DB: postgres
#   ports:
#     - "5132:5432"
#   volumes:
# #      TODO: RENAME dlh_database_pg
#     - ./data/dlh_database_pg/:/var/lib/postgresql/data
#     - ./dlh_database_pg/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
#   healthcheck:
#     test: [ "CMD", "pg_isready", "-U", "postgres" ]
#     interval: 10s
#     retries: 5
#   restart: always

volumes:
  redis_data:

networks:
  app-network:
    driver: bridge
